#----------------------------------------
HIPCC    = ${HOME}/FloatGuard/gdb_script/hipcc_wrapper.sh
HIPFLAGS = -g -O0
LINKFLAGS = -fgpu-rdc --hip-link 
#----------------------------------------

InstStub.o:
	${HIPCC} ${HIPFLAGS} -D__HIP_PLATFORM_AMD__ -c InstStub.cpp

.PHONY: clean

clean:
	rm -f *.o